# task base setting
task_name: "Insert Marker"
dataset_name: "insert marker"
env_name: "InsertMarker"
subtask_language_info: [["Pick up marker"], ["insert marker to the pen_holder"]]  # get form task discription (LLM)
subtask_object_info: [["gripper", "marker"], ["marker", "pen_holder"]] # object discription, first is the moving object, second is the target object
obj_info:
  labels: ["marker", "pen_holder"] # object label, get from task discription (LLM)
  poses: [[-0.3467163,  0.44472795,  0.04,  0.707, 0, 0,  0.707], [-0.49747796,  0.2556481,  0.04,  1, 0, 0,  0]] # object 6-Dof pose, get from pose estimation
  grasp_obj: [True, False] # object proptery, graspable or static, get from task discription (LLM)
robot_init_qpos: [-1.01362259, -1.74503436, 1.85383064, -1.64450421, -1.57473976, -0.25406391]
schedule_random: false

# agent base setting
agent_name: "LaNE"
device: "cuda"
train_camera_name: "sceneview" # choose camera for training
is_finetuning: false

# reward model setting
reward_model_type: "test" # test, online, offline, action_feasible. test use the reward model in the environment
reward_scale: 100
use_pre_reward: false
save_online_image: true # save online vlm image, save image for train reward model
offline_reward_model_path: "./experiments/offline_reward_model/${task_name}/best_reward_model.pth" # path to the offline reward model
action_feasible_model_path: "./experiments/action_feasible_model/${task_name}/best_reward_model.pth" # path to the action feasible model

now: ${now:%Y-%m-%d}-${now:%H-%M-%S}
save_dir: ./experiments/${task_name}/${dataset_name}-${env_name}-${agent_name}-${reward_model_type}-${now}
# load all the default settings
defaults:
  - environment: base_env
  - agent: lane_policy
  # - finetuning: lane_policy_finetuning

hydra:
    name: ${task_name}
    run:
        dir: ${save_dir}
