bounds_min: &bounds_min [-0.45, -0.75, 0.698]
bounds_max: &bounds_max [0.10, 0.60, 1.2]
device: &device 'cuda'
seed: &seed 0

constraint_generator:
  model: chatgpt-4o-latest
  temperature: 0.0
  max_tokens: 2048

keypoint_proposer:
  num_candidates_per_mask: 5
  min_dist_bt_keypoints: 0.06
  max_mask_ratio: 0.5
  device: *device
  bounds_min: *bounds_min
  bounds_max: *bounds_max
  seed: *seed