# task base setting
task_name: "Pick up banana"
dataset_name: "pick up banana"
env_name: "PickBanana"
subtask_language_info: [["Pick up banana"]]  # get form task discription (LLM)
subtask_object_info: [["gripper", "banana"]] # object discription, first is the moving object, second is the target object
obj_info:
  labels: ["banana"] # object label, get from task discription (LLM)
  poses: [[-0.29156371, 0.37589715, 0.04, 0.707, 0, 0, 0.707]] # object 6-Dof pose, get from pose estimation
  grasp_obj: [true] # object proptery, graspable or static, get from task discription (LLM)
robot_init_qpos: [-1.01362259, -1.74503436, 1.85383064, -1.64450421, -1.57473976, -0.25406391]

# agent base setting
agent_name: "LaNE"
device: "cuda"
train_camera_name: "sceneview" # choose camera for training

# reward model setting
reward_model_type: "test" # test, online, offline. test use the reward model in the environment
reward_scale: 100
use_pre_reward: false

now: ${now:%Y-%m-%d}-${now:%H-%M-%S}
save_dir: ./experiments/${task_name}/${dataset_name}-${env_name}-${agent_name}-${reward_model_type}-${now}
# load all the default settings
defaults:
  - environment: base_env
  - agent: lane_policy

hydra:
    name: ${task_name}
    run:
        dir: ${save_dir}
