# task base setting
task_name: "insert marker"
dataset_name: "insert marker"
env_name: "InsertMarker"
subtask_language_info: ["Pick up marker", "insert marker to the pen_holder"]  # get form task discription (LLM)
subtask_object_info: [["gripper", "marker"], ["marker", "pen_holder"]] # object discription, first is the moving object, second is the target object
obj_info:
  labels: ["marker", "pen_holder"] # object label, get from task discription (LLM)
  poses: [[-0.33288363209095, 0.2773848510654575, 0.08, 0.707, 0, 0, 0.707], [-0.37417705225104425, 0.5138674168057255, 0, 1, 0, 0, 0]] # object 6-Dof pose, get from pose estimation
  grasp_obj: [True, False] # object proptery, graspable or static, get from task discription (LLM)
robot_init_qpos: [-1.0193360487567347, -1.6555258236327113, 2.0492919127093714, -1.9293281040587367, -1.5750640074359339, -0.2582805792437952]
schedule_random: false
subtask_max_step: 50

# agent base setting
mode: "train" # train, eval, replay
agent_name: "LaNE"
device: "cuda"
train_camera_name: "sceneview" # choose camera for training
is_finetuning: false

# reward model setting
reward_model_type: "test" # test, online, offline, action_feasible. test use the reward model in the environment
reward_scale: 100
use_pre_reward: false
save_online_image: true # save online vlm image, save image for train reward model
offline_reward_model_path: "./experiments/offline_reward_model/${task_name}/best_reward_model.pth" # path to the offline reward model
action_feasible_model_path: "./experiments/action_feasible_model/${task_name}/best_reward_model.pth" # path to the action feasible model

now: ${now:%Y-%m-%d}-${now:%H-%M-%S}
save_dir: ./experiments/${task_name}/${dataset_name}-${env_name}-${agent_name}-${reward_model_type}-${now}
# load all the default settings
defaults:
  - environment: base_env
  - agent: lane_policy
  # - finetuning: lane_policy_finetuning

hydra:
    name: ${task_name}
    run:
        dir: ${save_dir}
