parameters:
  eye_on_hand: false
  freehand_robot_movement: false
  move_group: manipulator
  move_group_namespace: /
  namespace: /ur5_kinect_handeyecalibration_eye_on_base/
  robot_base_frame: base
  robot_effector_frame: tool0_controller
  tracking_base_frame: camera_color_frame
  tracking_marker_frame: camera_marker
transformation:
  qw: 0.21026752269102125
  qx: -0.3387571036468993
  qy: 0.7852201296160757
  qz: -0.47377266877254315
  x: -0.7191124650889854
  y: 0.6420244241334043
  z: 0.5274728553604324
